#!/bin/bash

IN_SLIPSTREAM=0

NEW_USER=${NEW_USER:-edugain}

if [ $IN_SLIPSTREAM == 1 ]
then
	username=$(cat /opt/slipstream/client/bin/slipstream.context | grep username | sed 's/username = //g')
	cat /opt/slipstream/client/bin/slipstream.context | grep cookie | sed 's/cookie = //g' > /root/.slipstream-cookie
	ss-user-get $username 1> /root/user.xml
	user_mail=$(cat /root/user.xml | sed 's/ /\n/g' | grep email= | sed 's/email=//g' | sed 's/"//g')
	ss-display "$username has mail $user_mail"
	EDUGAIN_EMAIL=$user_mail
else
	EDUGAIN_EMAIL=${EDUGAIN_EMAIL:-bryan.brancotte@france-bioinformatique.fr}
fi


useradd $NEW_USER -m -s /bin/bash 
wget -O - https://raw.githubusercontent.com/cyclone-project/cyclone-python-pam/master/setup.sh | sh

echo "{
  \"ports\":[[20000, 25000] ]
}" > /lib/security/cyclone_config 

cp /etc/pam.d/sshd /etc/pam.d/sshd.bak
cat /etc/pam.d/sshd.bak | sed 's/auth /#auth /g' | sed 's/# #auth /auth /g' > /etc/pam.d/sshd

echo "{
  \"users\": [
    \"$EDUGAIN_EMAIL\"
  ]
}" >> /home/$NEW_USER/.edugain

hostname $(hostname -I | sed 's/ /\n/g' | head -n 1)

#sed -i.bak '/Press enter to continue/d' /lib/security/cyclone_pam.py 

service ssh restart
